# Generated by Django 6.0.1 on 2026-02-03 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('engine', models.CharField(max_length=100)),
                ('passengers_people', models.PositiveIntegerField()),
                ('type_engine', models.CharField(max_length=100)),
                ('trunk', models.PositiveIntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='car.color', verbose_name='цвет')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.company', verbose_name='компания производитель')),
            ],
        ),
    ]
