# Generated by Django 6.0.2 on 2026-02-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0003_alter_cpu_cores_alter_gpu_memory_alter_pc_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='status_cpu',
            field=models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD'), ('Ryzen', 'Рузен')], default='Intel', max_length=20),
        ),
        migrations.AddField(
            model_name='ram',
            name='status_ram',
            field=models.CharField(choices=[('DDR2', 'ДДР2'), ('DDR3', 'ДДР3'), ('DDR4', 'ДДР4')], default='DDR2', max_length=20),
        ),
    ]
