# Generated by Django 6.0.2 on 2026-02-04 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='cpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cpu', to='pc.cpu', verbose_name='проц'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='gpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Gpu', to='pc.gpu', verbose_name='видюха'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Manufacturer', to='pc.manufacturer', verbose_name='производитель'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ram', to='pc.ram', verbose_name='оперативка'),
        ),
    ]
