# Generated by Django 6.0.2 on 2026-02-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0002_alter_pc_cpu_alter_pc_gpu_alter_pc_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='cores',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='memory',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pc',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ram',
            name='size',
            field=models.PositiveIntegerField(),
        ),
    ]
